const carDatabase = [
    {
        id: "megane4_13",
        brand: "Renault",
        model: "Megane 4 1.3 TCe",
        stockHP: 140,
        stockNM: 240,
        tunedHP: "155 - 160",
        tunedNM: "260 - 270",
        imageUrl: "https://arabavs.com/images/car_images/6_6_377af_14.jpg", 
        warnings: ["Folosire benzină premium (cifră octanică 98/100).", "Schimb de ulei la maxim 10.000 km."]
    },
    {
        id: "bmw_f10_535d",
        brand: "BMW",
        model: "Seria 5 F10 535d",
        stockHP: 313,
        stockNM: 630,
        tunedHP: "350 - 360",
        tunedNM: "700 - 710",
        imageUrl: "https://th.bing.com/th/id/R.cd2383c6292d19fb42993488ca1ce102?rik=dnpKU%2fSQNWd8Ig&riu=http%3a%2f%2fwww.automobilesreview.com%2fgallery%2fbmw-5-series-f10-sports-package%2fbmw-f10-m-sports-package-01.jpg&ehk=mXkBGe7HZsMTDVBdM2Q5CCUtvK2sprIuugk%2fhGWLJiU%3d&risl=&pid=ImgRaw&r=0",
        warnings: ["Revizie la turbocompresoare (small & big turbo) recomandată anterior resoftării.", "Atenție la uzura convertizorului de cuplu din cutia automată (ZF 8HP)."]
    },
    {
        id: "vw_golf7_20tdi",
        brand: "Volkswagen",
        model: "Golf 7 2.0 TDI",
        stockHP: 150,
        stockNM: 340,
        tunedHP: "180 - 185",
        tunedNM: "390 - 400",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.PuzvkZYsiu-fmxQVdpax3gHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Regenerările DPF-ului vor fi monitorizate atent.", "Nu se va abuza de accelerație sub 2000 RPM pentru a proteja ambreiajul."]
    },
    {
        id: "skoda_octavia3_rs",
        brand: "Skoda",
        model: "Octavia 3 RS 2.0 TSI",
        stockHP: 220,
        stockNM: 350,
        tunedHP: "275 - 285",
        tunedNM: "420 - 430",
        imageUrl: "https://tse3.mm.bing.net/th/id/OIP.BRm1cBLDjr6lhB_ZRPYengHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Recomandare montare bujii mai reci.", "Upgrade admisie recomandat pentru performanță maximă."]
    },
    {
        id: "dacia_duster_15dci",
        brand: "Dacia",
        model: "Duster 1.5 dCi",
        stockHP: 110,
        stockNM: 260,
        tunedHP: "125 - 130",
        tunedNM: "290 - 300",
        imageUrl: "https://img.tipcars.com/fotky_velke/54004801_1/1771761854/E/dacia-duster-1-5-blue-dci-4x4-serv-kniha.jpg",
        warnings: ["Verificare injectoare înainte de resoftare.", "Timp de răcire la ralanti de 1 minut după drumuri lungi."]
    },
    {
        id: "audi_a4b9_20tfsi",
        brand: "Audi",
        model: "A4 B9 2.0 TFSI",
        stockHP: 252,
        stockNM: 370,
        tunedHP: "290 - 300",
        tunedNM: "420 - 430",
        imageUrl: "https://th.bing.com/th/id/R.db33090bb7f01e5fd55f04a1d89c4369?rik=AQSE85ToMMuz%2fg&pid=ImgRaw&r=0",
        warnings: ["Revizie la cutia S-Tronic obligatorie dacă a depășit 60k km.", "Piesele de aprindere trebuie să fie în stare perfectă."]
    },
    {
        id: "mercedes_w205_c220d",
        brand: "Mercedes-Benz",
        model: "C-Class W205 C220d",
        stockHP: 170,
        stockNM: 400,
        tunedHP: "195 - 200",
        tunedNM: "450 - 460",
        imageUrl: "https://garagem360.com.br/wp-content/uploads/2021/01/Mercedes-Benz-C300-Sport-2018-Car-Blog-1-1024x768.jpg",
        warnings: ["Răcire adecvată a motorului în mers sportiv.", "Calitate superioară a motorinei recomandată."]
    },
    {
        id: "ford_mustang_23",
        brand: "Ford",
        model: "Mustang VI 2.3 EcoBoost",
        stockHP: 317,
        stockNM: 432,
        tunedHP: "330 - 340",
        tunedNM: "480 - 500",
        imageUrl: "https://rsmmotors.com/wp-content/uploads/2019/10/69194_2886_4326.jpg",
        warnings: ["Upgrade intercooler recomandat urgent (stock se supraîncălzește).", "Limitare de cuplu pe treptele 1 și 2 pentru aderență."]
    },
    {
        id: "porsche_macan_30v6",
        brand: "Porsche",
        model: "Macan S 3.0 V6",
        stockHP: 340,
        stockNM: 460,
        tunedHP: "380 - 390",
        tunedNM: "520 - 540",
        imageUrl: "https://www.pch-automotive.be/images/voiture/max/69756.jpg",
        warnings: ["Întreținere strictă a cutiei PDK.", "Revizie completă distribuție înainte de tuning intens."]
    },
    {
        id: "alfa_giulia_22",
        brand: "Alfa Romeo",
        model: "Giulia 2.2 JTDM",
        stockHP: 180,
        stockNM: 450,
        tunedHP: "210 - 215",
        tunedNM: "490 - 500",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.iOFucsZGMHiAjgOzl32ygAHaEF?w=5000&h=2758&rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Evitare reprize puternice la turații foarte joase.", "Curățare preventivă a admisiei (depuneri carbon)."]
    },
    {
        id: "vw_golf4_19tdi_alh",
        brand: "Volkswagen",
        model: "Golf 4 1.9 TDI (ALH)",
        stockHP: 90,
        stockNM: 210,
        tunedHP: "110 - 115",
        tunedNM: "250 - 260",
        imageUrl: "https://frankfurt.apollo.olxcdn.com/v1/files/l8wflf6pf4us3-BG/image;s=750x1000",
        warnings: ["Atenție la uzura volantei cu masă dublă.", "Verificare joc ax turbină înainte de resoftare."]
    },
    {
        id: "vw_golf5_20tdi_bkd",
        brand: "Volkswagen",
        model: "Golf 5 2.0 TDI (BKD)",
        stockHP: 140,
        stockNM: 320,
        tunedHP: "165 - 170",
        tunedNM: "370 - 380",
        imageUrl: "https://slike.autodiler.me/2022/8/30/AD315081298ME/1af4bc9d-2a95-457f-bf67-f5a567e4c253.webp",
        warnings: ["Risc de fisurare a chiulasei la modelele pre-2006 (cod A/B).", "Monitorizare presiune turbo pentru a evita 'limp mode'."]
    },
    {
        id: "vw_passat_b6_20tdi_bmp",
        brand: "Volkswagen",
        model: "Passat B6 2.0 TDI",
        stockHP: 140,
        stockNM: 320,
        tunedHP: "165 - 170",
        tunedNM: "370 - 380",
        imageUrl: "https://espirituracer.com/archivos/2024/06/volkswagen-passat-20-tdi-1.webp",
        warnings: ["Recomandată înlocuirea axului pompei de ulei (profil imbus).", "DPF-ul trebuie să fie în parametri normali."]
    },
    {
        id: "vw_passat_b8_20tdi_150",
        brand: "Volkswagen",
        model: "Passat B8 2.0 TDI",
        stockHP: 150,
        stockNM: 340,
        tunedHP: "180 - 185",
        tunedNM: "390 - 400",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.YBYbSpiM92rytsgKevPnTAHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Evitați subturarea pentru protejarea ambreiajului la cutiile manuale.", "Revizii DSG la maxim 60.000 km obligatorii."]
    },
    {
        id: "audi_a4_b8_20tdi",
        brand: "Audi",
        model: "A4 B8 2.0 TDI (CAGA)",
        stockHP: 143,
        stockNM: 320,
        tunedHP: "170 - 175",
        tunedNM: "370 - 380",
        imageUrl: "https://frankfurt.apollo.olxcdn.com/v1/files/iv2nh5ozlob01-RO/image;s=2364x1330",
        warnings: ["Posibile probleme cu pompa de înaltă presiune (pilitură).", "Verificare stare EGR și DPF."]
    },
    {
        id: "audi_a6_c7_30tdi",
        brand: "Audi",
        model: "A6 C7 3.0 TDI V6",
        stockHP: 245,
        stockNM: 500,
        tunedHP: "285 - 295",
        tunedNM: "570 - 580",
        imageUrl: "https://autospot.com.pl/panel/uploads_uzywane/399/19745/AUTOSPOT----Audi-A6-TFSI-Quattro-12.jpg",
        warnings: ["Lanțul de distribuție poate deveni zgomotos, se recomandă verificare.", "Cutia S-Tronic necesită calibrare la softul de putere."]
    },
    {
        id: "audi_a3_8v_14tfsi",
        brand: "Audi",
        model: "A3 8V 1.4 TFSI",
        stockHP: 122,
        stockNM: 200,
        tunedHP: "145 - 150",
        tunedNM: "240 - 250",
        imageUrl: "https://tse3.mm.bing.net/th/id/OIP.ycU2_TgQ0sxOsuIwqIAJUwHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Folosire benzină de minim 98 CO.", "Uzura prematură a ambreiajului uscat din DSG7 (DQ200)."]
    },
    {
        id: "skoda_octavia2_19tdi",
        brand: "Skoda",
        model: "Octavia 2 1.9 TDI (BXE)",
        stockHP: 105,
        stockNM: 250,
        tunedHP: "130 - 135",
        tunedNM: "290 - 300",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.UTS2h_LZJ42iWy1z0EW7OAHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Atenție la uzura axului cu came.", "Verificare cuzineți biele preventiv."]
    },
    {
        id: "skoda_superb3_20tsi_280",
        brand: "Skoda",
        model: "Superb 3 2.0 TSI",
        stockHP: 280,
        stockNM: 350,
        tunedHP: "330 - 340",
        tunedNM: "430 - 440",
        imageUrl: "https://car-guy.eu/wp-content/uploads/2021/07/IMG_1695-1-1024x768.jpg",
        warnings: ["Limitare cuplu treptele 1/2 pentru protecția DSG.", "Bujii reci și admisie sport recomandate (similar cu Golf R)."]
    },
    {
        id: "seat_leon_1m_18t",
        brand: "Seat",
        model: "Leon 1M 1.8T",
        stockHP: 180,
        stockNM: 235,
        tunedHP: "200 - 205",
        tunedNM: "290 - 300",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.VQo55cve7piIfBLi0BahTAHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Furtunurile de vacuum originale cedează ușor presiunii mărite.", "Recomandat bobine de inducție R8."]
    },
    {
        id: "seat_leon_5f_20tdi",
        brand: "Seat",
        model: "Leon 5F 2.0 TDI",
        stockHP: 150,
        stockNM: 340,
        tunedHP: "180 - 185",
        tunedNM: "390 - 400",
        imageUrl: "https://sportauspuff-guenstiger.de/pimg/zoom/eisenmann/seat-leon-5f-cupra-st-2-0-tsi-eisenmann-sportauspuff-s1100-01202s.jpg",
        warnings: ["Răcirea lichidului de frână poate fi insuficientă la mers sportiv.", "Tuning recomandat cu păstrarea DPF-ului activ."]
    },
    {
        id: "vw_touareg_7p_30tdi",
        brand: "Volkswagen",
        model: "Touareg 7P 3.0 TDI",
        stockHP: 245,
        stockNM: 550,
        tunedHP: "285 - 290",
        tunedNM: "600 - 620",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.wL543zlQBOdP6SLCqhJpxwHaEX?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Sarcină termică ridicată, nu opriți motorul imediat după drum lung.", "Atenție la etanșările injectoarelor (șaibe cupru)."]
    },
    {
        id: "vw_transporter_t5_25tdi",
        brand: "Volkswagen",
        model: "Transporter T5 2.5 TDI",
        stockHP: 131,
        stockNM: 340,
        tunedHP: "155 - 160",
        tunedNM: "380 - 390",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.zHzUDm6skcweQoVaczAyDAHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Turbina este solicitată, se recomandă verificare uzură lagăre.", "Galeria de evacuare se poate fisura din cauza temperaturilor EGT mari."]
    },
    {
        id: "bmw_e46_320d_150",
        brand: "BMW",
        model: "Seria 3 E46 320d",
        stockHP: 150,
        stockNM: 330,
        tunedHP: "175 - 180",
        tunedNM: "380 - 390",
        imageUrl: "https://tse1.mm.bing.net/th/id/OIP.s01qH7gHTDvA7itlwAv0HAHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Anularea clapetelor de admisie (swirl flaps) este esențială înainte de soft.", "Curățare valvă PCV."]
    },
    {
        id: "bmw_e90_320d_m47",
        brand: "BMW",
        model: "Seria 3 E90 320d (M47)",
        stockHP: 163,
        stockNM: 340,
        tunedHP: "190 - 195",
        tunedNM: "390 - 400",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.XmO_tHov5_zQw2nNKJ8N0wHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Termostatele defecte nu lasă DPF-ul să își facă regenerarea.", "Verificare furtun intercooler (deseori fisurat)."]
    },
    {
        id: "bmw_f30_320d_n47",
        brand: "BMW",
        model: "Seria 3 F30 320d (N47)",
        stockHP: 184,
        stockNM: 380,
        tunedHP: "210 - 215",
        tunedNM: "420 - 430",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.vUvyDiEw8qQ_6FYxMiGgNgHaFj?w=1024&h=768&rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Distribuția trebuie să fie schimbată/verificată înainte de resoftare.", "Curățare admisie de depuneri de calamină."]
    },
    {
        id: "bmw_g20_m340i",
        brand: "BMW",
        model: "Seria 3 G20 M340i (B58)",
        stockHP: 374,
        stockNM: 500,
        tunedHP: "410 - 420",
        tunedNM: "560 - 580",
        imageUrl: "https://tse3.mm.bing.net/th/id/OIP.9nnXNjuDooY3YZdGWAZlYQHaFi?w=480&h=359&rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["ECU blocat (Bosch MG1) necesită deblocare (Bench/Unlock).", "Cea mai fiabilă platformă de tuning recentă, doar ulei de calitate necesar."]
    },
    {
        id: "bmw_e60_530d",
        brand: "BMW",
        model: "Seria 5 E60 530d (M57)",
        stockHP: 218,
        stockNM: 500,
        tunedHP: "255 - 265",
        tunedNM: "560 - 580",
        imageUrl: "https://i.ytimg.com/vi/orM3iNUZDhw/maxresdefault.jpg",
        warnings: ["Eliminare clapete admisie obligatorie.", "Galeria de evacuare de fontă o poate crăpa pe cea de tablă (upgrade recomandat)."]
    },
    {
        id: "bmw_f10_520d",
        brand: "BMW",
        model: "Seria 5 F10 520d (N47)",
        stockHP: 184,
        stockNM: 380,
        tunedHP: "210 - 215",
        tunedNM: "420 - 430",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.Uq0-1yZhLhbg5mAPULNoVwHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Monitorizare DPF la exploatare exclusiv în oraș.", "Soft cutie xHP recomandat pentru a susține noul cuplu."]
    },
    {
        id: "bmw_x5_e70_30sd",
        brand: "BMW",
        model: "X5 E70 3.0sd (M57 BiTurbo)",
        stockHP: 286,
        stockNM: 580,
        tunedHP: "320 - 330",
        tunedNM: "640 - 650",
        imageUrl: "https://images1.autocasion.com/actualidad/wp-content/uploads/2011/08/BMW_x5_trasera-ok.jpg",
        warnings: ["Atenție la starea turbinei mici și a valvelor vacuumatice.", "Convertizorul cutiei 6HP poate patina dacă e uzat."]
    },
    {
        id: "bmw_f20_116i",
        brand: "BMW",
        model: "Seria 1 F20 116i (N13)",
        stockHP: 136,
        stockNM: 220,
        tunedHP: "190 - 200",
        tunedNM: "290 - 300",
        imageUrl: "https://tse1.mm.bing.net/th/id/OIP.bRD-4uUvXCOGUiCEJZeqVAHaEU?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Motor identic cu 118i, dar limitat din soft, câștig masiv de putere.", "Sistemul de răcire trebuie monitorizat."]
    },
    {
        id: "dacia_logan2_15dci",
        brand: "Dacia",
        model: "Logan 2 1.5 dCi 90",
        stockHP: 90,
        stockNM: 220,
        tunedHP: "105 - 110",
        tunedNM: "250 - 260",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.1DQr3pf_kk1cttgXe9JxsQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Ambreiajul poate patina dacă accelerați brusc sub 2000 RPM în trepte mari.", "Verificare conducte retur injectoare."]
    },
    {
        id: "dacia_sandero_09tce",
        brand: "Dacia",
        model: "Sandero 0.9 TCe",
        stockHP: 90,
        stockNM: 140,
        tunedHP: "100 - 102",
        tunedNM: "155 - 160",
        imageUrl: "https://www.cinch.co.uk/used-cars/_next/image?url=https:%2F%2Feu.cdn.autosonshow.tv%2F6676%2F17710%2FYV68JFO%2F06_md.jpg&w=828&q=75",
        warnings: ["Bujii verificate la fiecare 30.000 km.", "Lanțul de distribuție poate fi fragil la stil de mers agresiv."]
    },
    {
        id: "renault_megane3_rs",
        brand: "Renault",
        model: "Megane 3 RS 2.0T",
        stockHP: 265,
        stockNM: 360,
        tunedHP: "290 - 300",
        tunedNM: "400 - 410",
        imageUrl: "https://carsguide-res.cloudinary.com/image/upload/f_auto,fl_lossy,q_auto,t_cg_hero_large/v1/editorial/Megane-RS-275-Trophy-2.jpg",
        warnings: ["Necesită benzină minim CO98.", "Kit intercooler majorat pentru randament constant pe circuit."]
    },
    {
        id: "renault_clio4_rs",
        brand: "Renault",
        model: "Clio 4 RS 1.6T",
        stockHP: 200,
        stockNM: 240,
        tunedHP: "220 - 225",
        tunedNM: "290 - 300",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.CJUpniLDfSkWhC0UZXymYwHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Cutia EDC poate suprasolicita ambreiajele, softul cutiei recomandat.", "Timp de răcire după track-days obligatoriu."]
    },
    {
        id: "renault_laguna3_20dci",
        brand: "Renault",
        model: "Laguna 3 2.0 dCi",
        stockHP: 150,
        stockNM: 340,
        tunedHP: "170 - 175",
        tunedNM: "380 - 390",
        imageUrl: "https://th.bing.com/th/id/R.a700fc80315f30924685d90a50d951fc?rik=mRPdM%2bwlrTBcZQ&pid=ImgRaw&r=0",
        warnings: ["Motor extrem de fiabil (M9R), doar ulei 5W30 C4 de calitate.", "Verificare clapeta EGR preventiv."]
    },
    {
        id: "ford_focus2_16tdci",
        brand: "Ford",
        model: "Focus Mk2 1.6 TDCi",
        stockHP: 109,
        stockNM: 240,
        tunedHP: "125 - 130",
        tunedNM: "270 - 280",
        imageUrl: "https://i0.shbdn.com/photos/47/60/61/lthmb_1191476061o2l.jpg",
        warnings: ["Sita de la conducta de ungere turbină trebuie scoasă preventiv.", "Atenție la scurgeri injectoare (garnituri cupru)."]
    },
    {
        id: "ford_focus3_st",
        brand: "Ford",
        model: "Focus Mk3 ST 2.0 EcoBoost",
        stockHP: 250,
        stockNM: 360,
        tunedHP: "270 - 275",
        tunedNM: "410 - 420",
        imageUrl: "https://th.bing.com/th/id/R.eaebf6d4abb4e7b7d9df7996e84f956d?rik=rAW3587h4eFf2w&pid=ImgRaw&r=0",
        warnings: ["Probleme frecvente tip 'LSPI' (Low Speed Pre-Ignition) – nu accelerați la podea la turații mici.", "Upgrade bujii necesar."]
    },
    {
        id: "ford_fiesta_st_16",
        brand: "Ford",
        model: "Fiesta Mk7 ST 1.6T",
        stockHP: 182,
        stockNM: 240,
        tunedHP: "200 - 205",
        tunedNM: "290 - 300",
        imageUrl: "https://f7432d8eadcf865aa9d9-9c672a3a4ecaaacdf2fee3b3e6fd2716.ssl.cf3.rackcdn.com/C2520/U1989/IMG_9461-large.jpg",
        warnings: ["Suport antibalans motor (torque mount) prea slab stock, recomandat upgrade.", "Răcire insuficientă pe admisie (intercooler stock mic)."]
    },
    {
        id: "ford_mondeo4_20tdci",
        brand: "Ford",
        model: "Mondeo Mk4 2.0 TDCi",
        stockHP: 140,
        stockNM: 320,
        tunedHP: "165 - 170",
        tunedNM: "370 - 380",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.R2c-yk4ANrcsUzTkMGTM8AHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Motorizare robustă, se pretează la tuning cu DPF activ.", "Uzura rulmentului de presiune și a volantei."]
    },
    {
        id: "ford_transit_22tdci",
        brand: "Ford",
        model: "Transit Custom 2.2 TDCi",
        stockHP: 125,
        stockNM: 350,
        tunedHP: "150 - 155",
        tunedNM: "390 - 400",
        imageUrl: "https://f7432d8eadcf865aa9d9-9c672a3a4ecaaacdf2fee3b3e6fd2716.ssl.cf3.rackcdn.com/C2408/U1875/IMG_32957-large.jpg",
        warnings: ["Risc de fisurare pistoane pe acest motor la regimuri de sarcină grea prelungită.", "Recomandare de a nu depăși limitările de greutate."]
    },
    {
        id: "opel_astra_h_19cdti",
        brand: "Opel",
        model: "Astra H 1.9 CDTi",
        stockHP: 150,
        stockNM: 320,
        tunedHP: "175 - 180",
        tunedNM: "380 - 390",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.9SvEnKsuKlJdUa0fT0jb0gHaEu?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Tija clapetelor de admisie swirl pică frecvent (anulare recomandată).", "Cutia de viteze M32 trebuie tratată cu grijă, rulmenții cedează."]
    },
    {
        id: "opel_insignia_a_20cdti",
        brand: "Opel",
        model: "Insignia A 2.0 CDTi",
        stockHP: 160,
        stockNM: 350,
        tunedHP: "185 - 190",
        tunedNM: "400 - 410",
        imageUrl: "https://th.bing.com/th/id/R.d40abbff4f67306aca5eefc736d69e71?rik=CMRXygCbc6P61Q&riu=http%3a%2f%2fipocars.com%2fimgs%2fa%2fg%2fa%2fx%2fq%2fopel__insignia_2_0_turbo_4x4_leather_1hd_climate_25tkm_2008_3_lgw.jpg&ehk=aarHvFl5D76WQ0jW0BGRktknUf1iDDowL4iHyV2Y2Oc%3d&risl=&pid=ImgRaw&r=0",
        warnings: ["Verificare O-ring pompă ulei (boală specifică) ÎNAINTE de orice.", "Furtunul intercooler tinde să crape de-a lungul îmbinării."]
    },
    {
        id: "opel_astra_j_14t",
        brand: "Opel",
        model: "Astra J 1.4 Turbo",
        stockHP: 140,
        stockNM: 200,
        tunedHP: "155 - 160",
        tunedNM: "230 - 240",
        imageUrl: "https://tse3.mm.bing.net/th/id/OIP.C8YsjBwpD8BgAkbcwp5rrgHaEA?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Sistemul PCV integrat în capacul culbutorilor cedează des.", "Risc de fisură a galeriei de evacuare/turbină."]
    },
    {
        id: "opel_vectra_c_19cdti",
        brand: "Opel",
        model: "Vectra C 1.9 CDTi",
        stockHP: 120,
        stockNM: 280,
        tunedHP: "145 - 150",
        tunedNM: "330 - 340",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.9nm1-IXkQZLcJVm68G2pWAHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Versiunea de 120cp cu 8 valve este mai robustă (fără clapete swirl).", "EGR necesită curățare constantă."]
    },
    {
        id: "opel_corsa_d_13cdti",
        brand: "Opel",
        model: "Corsa D 1.3 CDTi",
        stockHP: 90,
        stockNM: 200,
        tunedHP: "105 - 110",
        tunedNM: "230 - 240",
        imageUrl: "https://www.auto-data.net/images/f109/Opel-Corsa-D-5-door_1.jpg",
        warnings: ["Lanțul de distribuție este zgomotos, schimb preventiv.", "Volanta cu masă dublă foarte sensibilă."]
    },
    {
        id: "mercedes_w211_e220cdi",
        brand: "Mercedes-Benz",
        model: "E-Class W211 E220 CDI",
        stockHP: 150,
        stockNM: 340,
        tunedHP: "175 - 180",
        tunedNM: "390 - 400",
        imageUrl: "https://th.bing.com/th/id/R.516e08c5fa0f72a19c78220821b9da2c?rik=kbgaHs5Bgpc2ew&pid=ImgRaw&r=0",
        warnings: ["Cutia 5G-Tronic (722.6) e tanc, dar cere ulei proaspăt.", "SBC (frâne) trebuie verificat la reprezentanță."]
    },
    {
        id: "mercedes_w212_e350cdi",
        brand: "Mercedes-Benz",
        model: "E-Class W212 E350 CDI V6",
        stockHP: 265,
        stockNM: 620,
        tunedHP: "295 - 305",
        tunedNM: "680 - 690",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.ar30bDFpcbjLW6Pfq4tqrAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Garnitura de la răcitorul de ulei (sub turbină) are tendința să curgă.", "Releu bujii și galerie de admisie necesită atenție.","Pentru performanțe maxime,DPF/EGR off."]
    },
    {
        id: "mercedes_w204_c200cdi",
        brand: "Mercedes-Benz",
        model: "C-Class W204 C200 CDI",
        stockHP: 136,
        stockNM: 360,
        tunedHP: "165 - 175",
        tunedNM: "400 - 410",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.Vja3uaCgsllJdP966H7jbwHaE9?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Câștig imens de putere fiindcă motorul e identic cu C220 CDI (OM651).", "Injectoarele Delphi (la modelele timpurii) pot pica."]
    },
    {
        id: "mercedes_a45_amg_w176",
        brand: "Mercedes-Benz",
        model: "A-Class W176 A45 AMG",
        stockHP: 381,
        stockNM: 475,
        tunedHP: "400 - 410",
        tunedNM: "520 - 530",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.g2LY3XNhL7Re_ksoT6zpCAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Temperaturi foarte mari pe turbină, upgrade downpipe recomandat.", "Mentenanță cutie 7G-DCT vitală pentru launch control."]
    },
    {
        id: "mercedes_glc_250d",
        brand: "Mercedes-Benz",
        model: "GLC 250d X253",
        stockHP: 204,
        stockNM: 500,
        tunedHP: "220 - 230",
        tunedNM: "550 - 560",
        imageUrl: "https://tse1.mm.bing.net/th/id/OIP.7EkLeTmrbtNsx2ODuhrangHaEL?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Cutia 9G-Tronic limitează cuplul în primele 3 trepte.", "AdBlue (SCR) se recomandă a fi menținut funcțional dacă nu sunt erori."]
    },
    {
        id: "honda_civic_type_r_fk8",
        brand: "Honda",
        model: "Civic Type R FK8 2.0T",
        stockHP: 320,
        stockNM: 400,
        tunedHP: "340 - 350",
        tunedNM: "450 - 460",
        imageUrl: "https://tse2.mm.bing.net/th/id/OIP.wmeIAISO2knYARcxy1dyqQHaE8?w=768&h=512&rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Atenție la supraîncălzire motor pe track, upgrade grilă/radiator necesar.", "ECU necesită deblocare (Jailbreak) la modelele noi."]
    },
    {
        id: "honda_civic_15t",
        brand: "Honda",
        model: "Civic 1.5 VTEC Turbo",
        stockHP: 182,
        stockNM: 240,
        tunedHP: "205 - 210",
        tunedNM: "270 - 280",
        imageUrl: "https://www.dubicars.com/images/655b28/w_1300x760/carzaty/7c238ed9-9d17-4e49-af97-686dcb6f7e58.jpg",
        warnings: ["Dacă are cutie CVT, tuningul pe cuplu trebuie limitat drastic.", "Fenomenul de 'oil dilution' la distanțe scurte."]
    },
    {
        id: "peugeot_508_20hdi",
        brand: "Peugeot",
        model: "508 2.0 BlueHDi",
        stockHP: 180,
        stockNM: 400,
        tunedHP: "200 - 205",
        tunedNM: "440 - 450",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.-nb6d8xUT6bT_pc0XgDQOwHaFj?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Sistemul AdBlue are defect de fabrică frecvent (rezervor).", "Curea de distribuție inspectată preventiv."]
    },
    {
        id: "alfa_romeo_159_19jtdm",
        brand: "Alfa Romeo",
        model: "159 1.9 JTDm",
        stockHP: 150,
        stockNM: 320,
        tunedHP: "175 - 180",
        tunedNM: "380 - 390",
        imageUrl: "https://tse1.mm.bing.net/th/id/OIP.d1dzdpqq8c8WkoKZhss1yAHaFj?w=1600&h=1200&rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Cutia M32 (la fel ca la Opel) are probleme cu rulmenții.", "Anulare și blindare clapete swirl admisie."]
    },
    {
        id: "volvo_xc60_d5",
        brand: "Volvo",
        model: "XC60 D5 2.4",
        stockHP: 215,
        stockNM: 440,
        tunedHP: "235 - 240",
        tunedNM: "480 - 490",
        imageUrl: "https://tse1.mm.bing.net/th/id/OIP.TY9b1NiENz9FhIAdBe_KnQHaE8?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Atenție la cureaua de accesorii (se rupe și intră în distribuție).", "Probleme uzuale cu întinzătorul mecanic."]
    },
    {
        id: "mini_cooper_s_f56",
        brand: "MINI",
        model: "Cooper S F56 2.0T",
        stockHP: 192,
        stockNM: 280,
        tunedHP: "240 - 250",
        tunedNM: "350 - 360",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.CHUtvB0KzBxMyCsLMtyOJAHaE6?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Motor identic cu JCW (B48), randament masiv.", "Suportul motor superior (dreapta) cedează sub cuplu."]
    },
    {
        id: "hyundai_i30_n",
        brand: "Hyundai",
        model: "i30 N 2.0 T-GDi",
        stockHP: 275,
        stockNM: 353,
        tunedHP: "300 - 310",
        tunedNM: "410 - 420",
        imageUrl: "https://tse1.mm.bing.net/th/id/OIP.QVID9COV5IqK1gYeQMKhJQHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Limitare presiune pe primele trepte pentru evitarea 'wheel hop'.", "Uleiul trebuie schimbat la sub 8000km în mers sportiv."]
    },
    {
        id: "toyota_yaris_gr",
        brand: "Toyota",
        model: "GR Yaris 1.6T",
        stockHP: 261,
        stockNM: 360,
        tunedHP: "285 - 295",
        tunedNM: "400 - 410",
        imageUrl: "https://tse1.mm.bing.net/th/id/OIP.stn4-favK-rySENNWLXAlAHaEK?w=892&h=502&rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Sistemul 4WD (GR-Four) se decuplează automat la supraîncălzire.", "Bujii reci esențiale."]
    },
    {
        id: "mazda_3_mps_bk",
        brand: "Mazda",
        model: "3 MPS 2.3 DISI",
        stockHP: 260,
        stockNM: 380,
        tunedHP: "280 - 285",
        tunedNM: "410 - 420",
        imageUrl: "https://tse3.mm.bing.net/th/id/OIP.b1YBT21G2bnddldT3O4vzwHaEK?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Upgrade pompă de înaltă presiune (HPFP) OBLIGATORIU înainte de resoftare.", "Lanț distribuție și VVT sensibile."]
    },
    {
        id: "fiat_abarth_595_competizione",
        brand: "Fiat",
        model: "Abarth 595 Competizione",
        stockHP: 180,
        stockNM: 250,
        tunedHP: "195 - 200",
        tunedNM: "290 - 300",
        imageUrl: "https://tse3.mm.bing.net/th/id/OIP.GJoM9BReT2cwGuYJtUPVywHaE7?rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Temperatură imensă sub capotă, upgrade admisie silicon.", "Turbina Garrett GT1446 este limitată, merge la limita maximă."]
    },
    {
        id: "bmw_e60_m5_v10",
        brand: "BMW",
        model: "M5 E60 5.0 V10",
        stockHP: 507,
        stockNM: 520,
        tunedHP: "525 - 535",
        tunedNM: "535 - 545",
        imageUrl: "https://tse1.mm.bing.net/th/id/OIP.2RuoJfz_7f7eKdjZ_keaIAHaE7?w=2000&h=1333&rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Înlocuirea cuzineților de bielă (rod bearings) este absolut obligatorie preventiv.", "Atenție la actuatoarele clapetelor de accelerație și pompa hidraulică SMG III."]
    },
    {
        id: "bmw_f01_730d",
        brand: "BMW",
        model: "Seria 7 F01 730d (N57)",
        stockHP: 245,
        stockNM: 540,
        tunedHP: "300 - 310",
        tunedNM: "620 - 640",
        imageUrl: "https://images.caradisiac.com/logos-ref/modele/modele--bmw-serie-7-f01/S0-modele--bmw-serie-7-f01.jpg",
        warnings: ["Distribuția pe lanț la motorul N57 trebuie verificată/schimbată preventiv.", "Clapetele swirl de pe galeria de admisie se pot rupe.", "Atenție la pompa de înaltă presiune (CP4) care este sensibilă la calitatea motorinei."]
    },
    {
        id: "bmw_f87_m2",
        brand: "BMW",
        model: "M2 F87 3.0T (N55)",
        stockHP: 370,
        stockNM: 465,
        tunedHP: "410 - 430",
        tunedNM: "560 - 580",
        imageUrl: "https://tse4.mm.bing.net/th/id/OIP.nsJD3FTvV7HPpHZPRVuaZwHaE7?w=2000&h=1333&rs=1&pid=ImgDetMain&o=7&rm=3",
        warnings: ["Chargepipe-ul de plastic cedează foarte ușor după resoftare; necesită upgrade la unul de aluminiu.", "Atenție la crank hub (piulița de la arbore) la creșteri mari de cuplu și turație.", "Bujiile trebuie schimbate la intervale mai scurte după Stage 1."]
    },
    {
        id: "subaru_forester_xv_20d",
        brand: "Subaru",
        model: "Forester / XV 2.0 Boxer Diesel",
        stockHP: 150,
        stockNM: 350,
        tunedHP: "180 - 190",
        tunedNM: "400 - 420",
        imageUrl: "https://th.bing.com/th/id/R.9fc0a48d0910edb93991ed99efc9d87c?rik=AcqF0Seie6f37A&riu=http%3a%2f%2fresources.carsguide.com.au%2fstyles%2fcg_hero_large%2fs3%2fdp%2falbums%2falbum-3237%2flg%2fSuabru_xv__12_.jpg&ehk=Xk0mgtbML1LXgVpJKHyZ7xtgN122uHHJqrJlfeZjI68%3d&risl=&pid=ImgRaw&r=0",
        warnings: ["Risc major de rupere a arborelui cotit (crankshaft) la primele generații de EE20.", "Ambreiajul pe versiunile manuale patinează ușor dacă cuplul este livrat prea brutal.", "Sistemul DPF este foarte sensibil la regimul de mers urban."]
    },
    {
        id: "renault_laguna_coupe_gt_20",
        brand: "Renault",
        model: "Laguna Coupe GT 2.0 dCi",
        stockHP: 180,
        stockNM: 400,
        tunedHP: "210 - 220",
        tunedNM: "460 - 480",
        imageUrl: "https://www.masculin.com/wp-content/uploads/sites/2/article/616-renault-laguna-coupe/laguna-coupe-n&b2-ga.jpg",
        warnings: ["Sistemul 4Control necesită mentenanță periodică (verificare bielete/actuator).", "Furtunul intercooler-ului tinde să crape sub presiune mărită.", "Motor extrem de robust (M9R), dar DPF-ul poate cauza probleme dacă nu sunt respectate regenerările."]
    },
    {
        id: "renault_laguna_coupe_30_v6",
        brand: "Renault",
        model: "Laguna Coupe 3.0 V6 dCi",
        stockHP: 235,
        stockNM: 450,
        tunedHP: "280 - 290",
        tunedNM: "540 - 560",
        imageUrl: "https://s1.cdn.autoevolution.com/images/gallery/RENAULT-Laguna-Coupe-3757_67.jpg",
        warnings: ["Motorul V9X are un spațiu foarte restrâns în compartimentul motor, mentenanța este costisitoare.", "Probleme frecvente la răcitorul de gaze EGR.", "Cutia de viteze automată Aisin necesită schimb regulat de ulei pentru a face față cuplului crescut."]
    },
    {
        id: "renault_laguna_coupe_35_v6",
        brand: "Renault",
        model: "Laguna Coupe 3.5 V6",
        stockHP: 240,
        stockNM: 330,
        tunedHP: "255 - 265",
        tunedNM: "350 - 365",
        imageUrl: "https://cdn.motor1.com/images/mgl/v3JnQ/s1/renault-laguna-coupe-monaco-gp-racing.jpg",
        warnings: ["Motor aspirat natural (VQ35DE - de proveniență Nissan), câștigurile de putere din soft sunt relativ mici.", "Atenție la consumul de ulei la turații ridicate și la etanșeitatea capacelor de culbutori.", "Termostatul și bobinele de inducție pot ceda odată cu vârsta."]
    }

];